### PR TITLE
Clear previous hpu_graphs when graph shape changed to save memory

### PR DESCRIPTION
**Pull request by BaihuiJin**
# What does this PR do?

Test on Llama-7b shows tgi-gaudi generates multiple hpu graphs when decoding shape changed by the increasing bs. On bf16 dtype, 128in 1024out scenario, the maximum bs is 32. If we use 64 threads to send concurrent requests the server will be OOM. the and the memory status in the debug info is demonstrated in figure1 and figure 2 respectively. Every graph keeps a copy of kv cache, thus occupy a large part of the total memory.
image
image

Since the previous graph won't be used again as the bs won't shrink in the `recombine` function, we propose to record the current bs and remove previous graphs when bs changes to save memory. With this PR, on Llama7b 128in 1024out bf16 scenario, the max bs can increase to 64. The memory usage of bs32 and bs64 is listed  below. 
image
image

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by BaihuiJin** [comment]
@xt574chen plz help to review

**Comment by kdamaszk** [comment]
@BaihuiJin very interesting approach!
I have one question -- currently we are warming up all decode batch sizes to avoid graph compilation in runtime. Does your change will trigger GC after HPU graph change or will only call record HPU graph again?

**Comment by xt574chen** [comment]
@kdamaszk .clear_cache() should only clear the HPU Graph cache instead of the Synapse Graph cache. @BaihuiJin Pls share your performance data on LlaMA2-7B to double-check.

**Review by xt574chen — APPROVED** [review]
Looks good to me.

**Comment by BaihuiJin** [comment]
> @BaihuiJin very interesting approach! I have one question -- currently we are warming up all decode batch sizes to avoid graph compilation in runtime. Does your change will trigger GC after HPU graph change or will only call record HPU graph again?

cc @xt574chen 
To simplify the question, I disabled the warmup and changed the logic to clear cache regardless of the bs change(remove the if condition), and get profiling result for 8 iteration with the same bs. The server behavior is shown by fig1, and the profile result is shown by fig2. 
image
image
We can see the recording of hpu graph happened.

On the other hand, in the same case, I dumped hpu_graphs and counted the number, the total number of graphs is 94(pre+post) in the 128 in 128out bs32 requests_num 500 scenario. If recompile happens every time after clear cache happens, the number of total graphs should be far more than 94, I think that proves recompile did not happen.

**Review by kdamaszk — APPROVED** [review]
LGTM

**Comment by BaihuiJin** [comment]
@regisss Could you help to review?

**Review by regisss — APPROVED** [review]
LGTM, nice!

**Comment by regisss** [comment]
@BaihuiJin There seems to be issues after this PR: https://github.com/huggingface/tgi-gaudi/issues/184

**Pull request merged**
