### PR TITLE
Remove the torch package in requirements.txt

### PR DESCRIPTION
**Pull request by yuanwu2017**
# What does this PR do?
It is easy to trigger the package not found error by using a mismatched docker image.
torch==2.4.0a0+git74cd574 corresponds to the following version of image. If you use the different pytorch image, it will trigger the error.
`vault.habana.ai/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.0:latest
`

Deleting this line can reduce the occurrence of this error, but it will also increase the risk of the torch package of gaudi being replaced, because other packages may require a higher version of torch, thus replacing it with a non-Gaudi version of torch. And you didn’t realize that the package had been changed.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by yuanwu2017** [comment]
@mandy-li @tthakkal @regisss  Please help to review.

**Review by tthakkal — APPROVED** [review]

**Review by tthakkal — APPROVED** [review]
LGTM
I was actually wondering why we had this in first place as torch was already part of docker image. thanks for removing.

**Review by mandy-li — APPROVED** [review]

**Comment by schoi-habana** [comment]
As you mentioned already, other packages can install non-gaudi version of pytorch. I experienced that a few times. Can we put a range of pytorch version to prevent the error instead of removing?

**Comment by regisss** [comment]
> As you mentioned already, other packages can install non-gaudi version of pytorch. I experienced that a few times. Can we put a range of pytorch version to prevent the error instead of removing?

I'm not sure adding a range of versions for `torch` will work. For example, with the 1.18 Docker image that has `torch 2.4.0a0+git74cd574`, running `pip install torch==2.4.0` will install the CPU version of Torch 2.4.0 from PyTorch repos. IMO the easiest solution is to not mention `torch` in the requirements. I guess most Gaudi users use the Docker images no?

**Comment by yuanwu2017** [comment]
There is no good way to solve this problem, because there is no public pypip source of Gaudi pytorch.

**Comment by regisss** [comment]
> There is no good way to solve this problem, because there is no public pypip source of Gaudi pytorch.

Yes, that's why I think it's better to not add `torch` to the requirements and that we expect users to use the official Gaudi Docker image (or a proper install of `habana_frameworks`).

**Pull request merged**
