### PR TITLE
Bulk shifting

### PR DESCRIPTION
**Pull request by jkaniecki**
1. shifting is implemented by roll'ing by a predefined list of chunks
2. kv-cache is shifted in bulk
3. right_padding is now calculated based on input_length and seq_length

Cherry-picked

### CODE REVIEW

**Comment by jkaniecki** [comment]
@regisss please review. Another cherry-picked change from dev branch.

**Review by kdamaszk — APPROVED** [review]

**Comment by jkaniecki** [comment]
@regisss - reminder

**Comment by kdamaszk** [comment]
@regisss please review

**Review by regisss — APPROVED** [review]
LGTM

@jkaniecki @kdamaszk No need to ping me several times, I don't forget PRs to review. And if there is any urgency, please say it clearly when requesting review at the beginning and I'll do my best to review as fast as possible.

**Pull request merged**
