### PR TITLE
updating Dockerfile with new version of habana software

### PR DESCRIPTION
**Pull request by ddmatthe**
# What does this PR do?

Fixes # (issue)
Updated dockerfile to work with newest version of firmware

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests? - we tested build by running Llama2-7b, llama2-70b, intel-neuarl-chat, and openhermes with tgi-gaudi container

## Who can review?

@OlivierDehaene OR @Narsil

### CODE REVIEW

**Comment by BaihuiJin** [comment]
I'm sorry if I'm wrong, but should the Deepspeed version also change to 1.16?

**Comment by vladimir-polin** [comment]
I think the dockerfile can updated to version of 1.17 image and deep speed

**Comment by leopck** [comment]
I agree with @vladimir-polin , let's bump this to 1.17.0, it was just released yesterday.

**Review by mgonchar — APPROVED** [review]
LGTM

**Review by mandy-li — CHANGES_REQUESTED** [review]
I am rejecting this PR. We will have a PR soon to upgrade everything to latest (Synapse 1.17 + OH 1.13.0)

**Comment by mandy-li** [comment]
Closing this PR without merging, see my comments above

**Pull request closed without merging**
