### PR TITLE
Simplify the warmup process

### PR DESCRIPTION
**Pull request by yuanwu2017**
No need to finish all the decode. Because the graphs generated by the remaining decode operations are no different from the previous ones.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by kdamaszk** [comment]
@yuanwu2017 thanks, it sounds reasonably. Did you check if number of compiled graphs is the same with and without your change?

**Comment by yuanwu2017** [comment]
Ok. Let me have a check.

**Comment by mandy-li** [comment]
@yuanwu2017 , what is the result of your checking?

**Comment by yuanwu2017** [comment]
@kdamaszk @mandy-li 
I attached the logs of before and after. You can check the "cache_len" in logs.  Both of them generated 37 graphs
[dbg_trace_after.log](https://github.com/user-attachments/files/16607541/dbg_trace_after.log)
[dbg_trace_before.log](https://github.com/user-attachments/files/16607544/dbg_trace_before.log)


command:
```
docker run -p 8080:80 \
   --runtime=habana \
   -v $volume:/data \
   -e HABANA_VISIBLE_DEVICES=all \
   -e OMPI_MCA_btl_vader_single_copy_mechanism=none \
   -e HF_HUB_ENABLE_HF_TRANSFER=1 \
   -e HUGGING_FACE_HUB_TOKEN=$hf_token \
   -e PREFILL_BATCH_BUCKET_SIZE=1 \
   -e BATCH_BUCKET_SIZE=16 \
   -e PAD_SEQUENCE_TO_MULTIPLE_OF=128 \
   --cap-add=sys_nice \
   --ipc=host \
   ghcr.io/huggingface/tgi-gaudi:2.0.1 \
   --model-id $model \
   --max-input-tokens 1024 \
   --max-batch-prefill-tokens 4096 \
   --max-total-tokens 2048 \
   --max-batch-size 16
```

source code:
Add the log in function wrapped_hpugraph_forward.

```
            cache[h] = CachedParams(graph_inputs, graph_outputs, graph, tinfo_list, asynchronous)
            dbg_trace('FROM_GRAPH', f'cache_len:{len(cache)}')

```

**Review by mandy-li — APPROVED** [review]

**Review by regisss — APPROVED** [review]

**Pull request merged**
