### PR TITLE
Rebase with TGI v2.0

### LINKED ISSUE #127: update the base image from 1.14 to 1.15
Currently the base image is from,
```sh
vault.habana.ai/gaudi-docker/1.14.0/ubuntu22.04/habanalabs/pytorch-installer-2.1.1:latest
```
to support the new model Mixtral-8x7B and other variants there is a need to upgrade to 1.15. 

Only upgrading the components of `optimum-habana -> 1.11.0` & `transformers -> 4.38.2` causes other issues
```sh
2024-04-10T21:55:13.283860Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/text_generation_server/server.py", line 68, in Warmup
2024-04-10T21:55:13.283861Z DEBUG text_generation_launcher:     self.model.warmup(batches)
2024-04-10T21:55:13.283862Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/text_generation_server/models/causal_lm.py", line 1080, in warmup
2024-04-10T21:55:13.283863Z DEBUG text_generation_launcher:     _, prefill_batch = self.generate_token([batches.pop(0)])
2024-04-10T21:55:13.283864Z DEBUG text_generation_launcher:   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
2024-04-10T21:55:13.283865Z DEBUG text_generation_launcher:     return func(*args, **kwds)
2024-04-10T21:55:13.283866Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/text_generation_server/models/causal_lm.py", line 918, in generate_token
2024-04-10T21:55:13.283868Z DEBUG text_generation_launcher:     batch.logits, batch.past = self.forward(
2024-04-10T21:55:13.283869Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/text_generation_server/models/causal_lm.py", line 818, in forward
2024-04-10T21:55:13.283870Z DEBUG text_generation_launcher:     outputs = self.model.forward(**kwargs)
2024-04-10T21:55:13.283872Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 661, in forward
2024-04-10T21:55:13.283873Z DEBUG text_generation_launcher:     return wrapped_hpugraph_forward(cache, stream, orig_fwd, args, kwargs, disable_tensor_cache, asynchronous, dry_run, max_graphs)
2024-04-10T21:55:13.283874Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 585, in wrapped_hpugraph_forward
2024-04-10T21:55:13.283875Z DEBUG text_generation_launcher:     cached.graph.replayV3(input_tensor_list, cached.asynchronous)
2024-04-10T21:55:13.283876Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 71, in replayV3
2024-04-10T21:55:13.283877Z DEBUG text_generation_launcher:     _hpu_C.replayV3(self.hpu_graph, tlistI, asynchronous)
2024-04-10T21:55:13.283878Z DEBUG text_generation_launcher: RuntimeError: [Rank:0] FATAL ERROR :: MODULE:PT_BRIDGE Exception in Launch thread...
2024-04-10T21:55:13.283880Z DEBUG text_generation_launcher: Check $HABANA_LOGS/ for details[Rank:0] FATAL ERROR :: MODULE:PT_LAZY Error, ValidateSyncInputTensors tensor_data is empty. Tensorid:41707 QueueStatus:ThreadPool m_tasks size: 1 irValue:id_110063_hpu__input
2024-04-10T21:55:13.283883Z DEBUG text_generation_launcher: [Rank:0] Habana exception raised from ValidateSyncInputTensors at hpu_lazy_tensors.cpp:875
```

- @regisss or others any help or hint here! (to enable supporting Mixtral-8x7B)
- Is there any plan or other PR for upgrading to 1.15.0?
- I am working on an upgrade but I might need some help

### PR DESCRIPTION
**Pull request by kdamaszk**
# What does this PR do?

Cherry-picks all changes between TGI v1.2.0 and v2.0. Updates the license to Apache 2.0

### CODE REVIEW

**Comment by kdamaszk** [comment]
@regisss  please review

**Comment by regisss** [comment]
@kdamaszk LGTM!

However, I get an error when I try to run Llama2-7b. I launch the server and send the same request as the example in the README: https://github.com/kdamaszk/tgi-gaudi/tree/rebase_tgi_2.0?tab=readme-ov-file#running-tgi-on-gaudi
And I get the following error:
```
ERROR generate{parameters=GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, frequency_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: Some(32), return_full_text: None, stop: [], truncate: None, watermark: false, details: false, decoder_input_details: false, seed: None, top_n_tokens: None, grammar: None }}:generate:generate_stream: text_generation_router::infer: router/src/infer.rs:145: `inputs` tokens + `max_new_tokens` must be <= 4096. Given: 4095 `inputs` tokens and 32 `max_new_tokens`
```
It seems that `max_new_tokens` is not considered when the input is padded to 4096 tokens. Are you able to reproduce it?

**Comment by yafshar** [comment]
The HPU Graph issue reported in https://github.com/huggingface/tgi-gaudi/issues/130 still exists. @regisss @kdamaszk if you give me permission, I can add the patch here. Or you can cherry pick the patch https://github.com/huggingface/tgi-gaudi/pull/129/commits/4963b7368eebf0a93d28bb8904780eca946aaadc to fix the issue.

**Comment by yafshar** [comment]
@regisss, for this update 1.15.0 & 1.15.1 the requirement is dill 0.3.8, from https://github.com/huggingface/tgi-gaudi/commit/4963b7368eebf0a93d28bb8904780eca946aaadc 
Currently the merge from tgi_gaudi:habama-main https://github.com/huggingface/tgi-gaudi/pull/134/commits/600d033c04a9d239d51081ff3d046005cdc8d663, installs the older one 0.3.7

**Comment by kdamaszk** [comment]
> @kdamaszk LGTM!
> 
> However, I get an error when I try to run Llama2-7b. I launch the server and send the same request as the example in the README: https://github.com/kdamaszk/tgi-gaudi/tree/rebase_tgi_2.0?tab=readme-ov-file#running-tgi-on-gaudi And I get the following error:
> 
> ```
> ERROR generate{parameters=GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, frequency_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: Some(32), return_full_text: None, stop: [], truncate: None, watermark: false, details: false, decoder_input_details: false, seed: None, top_n_tokens: None, grammar: None }}:generate:generate_stream: text_generation_router::infer: router/src/infer.rs:145: `inputs` tokens + `max_new_tokens` must be <= 4096. Given: 4095 `inputs` tokens and 32 `max_new_tokens`
> ```
> 
> It seems that `max_new_tokens` is not considered when the input is padded to 4096 tokens. Are you able to reproduce it?

@regisss you are right. This issue is caused by new default params for `max-input-length` and `max-total-tokens` (before 1024 and 2048, now 4095 and 4096). I will modify README example to set these params properly, WDYT?

**Comment by kdamaszk** [comment]
> The HPU Graph issue reported in #130 still exists. @regisss @kdamaszk if you give me permission, I can add the patch here. Or you can cherry pick the patch [4963b73](https://github.com/huggingface/tgi-gaudi/commit/4963b7368eebf0a93d28bb8904780eca946aaadc) to fix the issue.

thanks @yafshar, I will cherry-pick this commit

**Comment by regisss** [comment]
> > @kdamaszk LGTM!
> > However, I get an error when I try to run Llama2-7b. I launch the server and send the same request as the example in the README: https://github.com/kdamaszk/tgi-gaudi/tree/rebase_tgi_2.0?tab=readme-ov-file#running-tgi-on-gaudi And I get the following error:
> > ```
> > ERROR generate{parameters=GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, frequency_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: Some(32), return_full_text: None, stop: [], truncate: None, watermark: false, details: false, decoder_input_details: false, seed: None, top_n_tokens: None, grammar: None }}:generate:generate_stream: text_generation_router::infer: router/src/infer.rs:145: `inputs` tokens + `max_new_tokens` must be <= 4096. Given: 4095 `inputs` tokens and 32 `max_new_tokens`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems that `max_new_tokens` is not considered when the input is padded to 4096 tokens. Are you able to reproduce it?
> 
> @regisss you are right. This issue is caused by new default params for `max-input-length` and `max-total-tokens` (before 1024 and 2048, now 4095 and 4096). I will modify README example to set these params properly, WDYT?

Sounds good!

**Review by regisss — APPROVED** [review]
LGTM!

Side note, I cannot stop the Docker container with ctrl+c anymore. Not a big deal, maybe it's not even related to TGI Gaudi.

**Comment by kdamaszk** [comment]
> LGTM!
> 
> Side note, I cannot stop the Docker container with ctrl+c anymore. Not a big deal, maybe it's not even related to TGI Gaudi.

Right, I observed the same behavior. This is caused by this PR: https://github.com/huggingface/text-generation-inference/pull/1716. Due to that, the tgi_entrypoint.sh is run instead of text-generation-launcher.
I'm not sure what is the purpose of this change. We can come back to the previous solution if you want -- it was more user-friendly.

**Comment by regisss** [comment]
> 
> Right, I observed the same behavior. This is caused by this PR: [huggingface#1716](https://github.com/huggingface/text-generation-inference/pull/1716). Due to that, the tgi_entrypoint.sh is run instead of text-generation-launcher. I'm not sure what is the purpose of this change. We can come back to the previous solution if you want -- it was more user-friendly.

Okay I see. Let me discuss that with TGI maintainers to see if we want to directly modify this there.

**Pull request merged**
