### PR TITLE
correct input_length since habana extend input_length to max_input_le…

### PR DESCRIPTION
**Pull request by sywangyi**
…ngth

or else max_new_tokens in stopcriteria will be incorrect

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sywangyi** [comment]
@regisss please help review.
or else, max_new_tokens is incorrect. and will pop error in https://github.com/huggingface/tgi-gaudi/blob/habana-main/server/text_generation_server/models/causal_lm.py#L867

**Comment by regisss** [comment]
Have you set `--max-input-length` and `--max-total-tokens` as described [here](https://github.com/huggingface/tgi-gaudi?tab=readme-ov-file#setup-tgi)?

**Comment by sywangyi** [comment]
> Have you set `--max-input-length` and `--max-total-tokens` as described [here](https://github.com/huggingface/tgi-gaudi?tab=readme-ov-file#setup-tgi)?

yes，I have set

**Comment by regisss** [comment]
Any idea why this is happening @kdamaszk ?

**Comment by kdamaszk** [comment]
@sywangyi I assume that you are not setting max_new_tokens per request. That's why it is calculated based on input_length.
This change looks good to me, but we have to run some tests to verify if it doesn't break anything else.
@jkaniecki can you verify this change?

**Comment by sywangyi** [comment]
other issue that the PR should address 
b'data:{"error":"Input validation error: `inputs` tokens + `max_new_tokens` must be <= 2048. Given: 2115 `inputs` tokens and 512 `max_new_tokens`","error_type":"validation"}\n\n'

since input length is not truncated.

**Comment by sywangyi** [comment]
@jkaniecki any update about the test?

**Review by jkaniecki — APPROVED** [review]
Tested, approved - @regisss , please review

**Review by kdamaszk — APPROVED** [review]

**Review by regisss — APPROVED** [review]

**Pull request merged**
