### PR TITLE
Revert "Dev/mask ldconfig output v2 (#1716)"

### PR DESCRIPTION
**Pull request by kdamaszk**
This reverts commit 194fcb4a3de0e636415f476b46f2ffc7d7e50aee.

# What does this PR do?

Fixes closing docker with Ctrl+C

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by kdamaszk** [comment]
@regisss please review

**Comment by regisss** [comment]
@kdamaszk Would cherry-picking this PR work? https://github.com/huggingface/text-generation-inference/pull/1910

**Comment by kdamaszk** [comment]
@regisss The change you mentioned cannot be cherry-picked at this moment, because it modifies code that is not yet present in tgi-gaudi (was introduced after 2.0.0).
In that case, we should probably rebase with latest TGI release soon.

**Comment by regisss** [comment]
@kdamaszk Ah you're right, I didn't think about that. From what I see, it is not part of the latest release (v2.0.3) so we would probably need to wait for v2.1, which I don't think will be released in the next few days.
In the meantime, maybe we can continue with this PR. WDYT?

**Comment by kdamaszk** [comment]
@regisss sound good for me

**Review by regisss — APPROVED** [review]

**Pull request merged**
