### PR TITLE
Control prefill and decode batch size separately

### PR DESCRIPTION
**Pull request by kdamaszk**
This PR allows to control prefill and decode batch size separately. It is quite important, because in general we should prefer smaller number of request in prefill operation than in decode.
Also it includes padding on output tokens during token budget calculations.

### CODE REVIEW

**Comment by kdamaszk** [comment]
@regisss please take a look on this.

**Review by regisss — APPROVED** [review]
LGTM!

We should prefer less requests for prefill than for decode because we get better performance with smaller batches for prefill?

**Comment by kdamaszk** [comment]
> LGTM!
> 
> We should prefer less requests for prefill than for decode because we get better performance with smaller batches for prefill?

Exactly, too huge prefill batch size will cause first token latency to be very large. Moreover, requests are coming asynchronously and we want to prefill them as fast as possible -- waiting for more request is tricky as we are not sure if they will come soon.

**Comment by regisss** [comment]
Makes sense, thanks for clarifying it!

**Pull request merged**
