### PR TITLE
Add support for Llava-next

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

Adding support for VL models and Llava-next in particular on Gaudi.

To launch a server, run for example:
```
docker run -p 8080:80 -v my_data_folder:/data --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none -e LOG_LEVEL=debug --cap-add=sys_nice --ipc=host tgi_gaudi --model-id llava-hf/llava-v1.6-mistral-7b-hf --max-input-tokens 3072 --max-total-tokens 4096
```

And you can send a request with:
```
curl -N 127.0.0.1:8080/generate_stream     -X POST     -d '{"inputs":"![](https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/transformers/rabbit.png)What is this a picture of?\n\n","parameters":{"max_new_tokens":16, "seed": 42}}'     -H 'Content-Type: application/json'
```

More information here: https://huggingface.co/docs/text-generation-inference/basic_tutorials/visual_language_models

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by regisss** [comment]
Getting this error for now after launching a server and sending a request as explained in the PR description:
```
2024-07-24T10:02:03.889671Z DEBUG text_generation_launcher: Traceback (most recent call last):
2024-07-24T10:02:03.889674Z DEBUG text_generation_launcher:   File "/usr/local/bin/text-generation-server", line 8, in <module>
2024-07-24T10:02:03.889680Z DEBUG text_generation_launcher:     sys.exit(app())
2024-07-24T10:02:03.889683Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/typer/main.py", line 311, in __call__
2024-07-24T10:02:03.889687Z DEBUG text_generation_launcher:     return get_command(self)(*args, **kwargs)
2024-07-24T10:02:03.889690Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
2024-07-24T10:02:03.889693Z DEBUG text_generation_launcher:     return self.main(*args, **kwargs)
2024-07-24T10:02:03.889696Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/typer/core.py", line 778, in main
2024-07-24T10:02:03.889701Z DEBUG text_generation_launcher:     return _main(
2024-07-24T10:02:03.889706Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/typer/core.py", line 216, in _main
2024-07-24T10:02:03.889711Z DEBUG text_generation_launcher:     rv = self.invoke(ctx)
2024-07-24T10:02:03.889714Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
2024-07-24T10:02:03.889717Z DEBUG text_generation_launcher:     return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-07-24T10:02:03.889721Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
2024-07-24T10:02:03.889724Z DEBUG text_generation_launcher:     return ctx.invoke(self.callback, **ctx.params)
2024-07-24T10:02:03.889727Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
2024-07-24T10:02:03.889730Z DEBUG text_generation_launcher:     return __callback(*args, **kwargs)
2024-07-24T10:02:03.889735Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/typer/main.py", line 683, in wrapper
2024-07-24T10:02:03.889738Z DEBUG text_generation_launcher:     return callback(**use_params)  # type: ignore
2024-07-24T10:02:03.889741Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/text_generation_server/cli.py", line 137, in serve
2024-07-24T10:02:03.889744Z DEBUG text_generation_launcher:     server.serve(
2024-07-24T10:02:03.889748Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/text_generation_server/server.py", line 245, in serve
2024-07-24T10:02:03.889751Z DEBUG text_generation_launcher:     asyncio.run(
2024-07-24T10:02:03.889754Z DEBUG text_generation_launcher:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
2024-07-24T10:02:03.889757Z DEBUG text_generation_launcher:     return loop.run_until_complete(main)
2024-07-24T10:02:03.889761Z DEBUG text_generation_launcher:   File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
2024-07-24T10:02:03.889764Z DEBUG text_generation_launcher:     self.run_forever()
2024-07-24T10:02:03.889767Z DEBUG text_generation_launcher:   File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
2024-07-24T10:02:03.889770Z DEBUG text_generation_launcher:     self._run_once()
2024-07-24T10:02:03.889772Z DEBUG text_generation_launcher:   File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
2024-07-24T10:02:03.889775Z DEBUG text_generation_launcher:     handle._run()
2024-07-24T10:02:03.889778Z DEBUG text_generation_launcher:   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
2024-07-24T10:02:03.889781Z DEBUG text_generation_launcher:     self._context.run(self._callback, *self._args)
2024-07-24T10:02:03.889784Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
2024-07-24T10:02:03.889786Z DEBUG text_generation_launcher:     return await self.intercept(
2024-07-24T10:02:03.889789Z DEBUG text_generation_launcher: > File "/usr/local/lib/python3.10/dist-packages/text_generation_server/interceptor.py", line 25, in intercept
2024-07-24T10:02:03.889792Z DEBUG text_generation_launcher:     return await response
2024-07-24T10:02:03.889795Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
2024-07-24T10:02:03.889800Z DEBUG text_generation_launcher:     raise error
2024-07-24T10:02:03.889802Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
2024-07-24T10:02:03.889805Z DEBUG text_generation_launcher:     return await behavior(request_or_iterator, context)
2024-07-24T10:02:03.889808Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/text_generation_server/server.py", line 147, in Decode
2024-07-24T10:02:03.889811Z DEBUG text_generation_launcher:     generations, next_batch, timings = self.model.generate_token(batches)
2024-07-24T10:02:03.889814Z DEBUG text_generation_launcher:   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
2024-07-24T10:02:03.889816Z DEBUG text_generation_launcher:     return func(*args, **kwds)
2024-07-24T10:02:03.889820Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/text_generation_server/models/vlm_causal_lm.py", line 735, in generate_token
2024-07-24T10:02:03.889823Z DEBUG text_generation_launcher:     batch.logits = self.forward(
2024-07-24T10:02:03.889826Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/text_generation_server/models/vlm_causal_lm.py", line 595, in forward
2024-07-24T10:02:03.889829Z DEBUG text_generation_launcher:     outputs = self.model.forward(
2024-07-24T10:02:03.889832Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 716, in forward
2024-07-24T10:02:03.889835Z DEBUG text_generation_launcher:     return wrapped_hpugraph_forward(
2024-07-24T10:02:03.889838Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 590, in wrapped_hpugraph_forward
2024-07-24T10:02:03.889842Z DEBUG text_generation_launcher:     graph.capture_begin(dry_run=dry_run)
2024-07-24T10:02:03.889845Z DEBUG text_generation_launcher:   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 38, in capture_begin
2024-07-24T10:02:03.889848Z DEBUG text_generation_launcher:     _hpu_C.capture_begin(self.hpu_graph, dry_run)
2024-07-24T10:02:03.889851Z DEBUG text_generation_launcher: RuntimeError: [Rank:0] FATAL ERROR :: MODULE:PT_LAZY Error, ValidateSyncInputTensors tensor_data is empty. Tensorid:4986 QueueStatus:ThreadPool m_tasks size: 0 irValue:id_12556_hpu__input
```

**Comment by jmansdorfer** [comment]
@regisss I'm able to replicate this issue running on a bare metal Gaudi2 server running Synapse 1.16.0.

**Comment by yuanwu2017** [comment]
@regisss I just saw this patch of yours. I also enabled llava-next in [PR187](https://github.com/huggingface/tgi-gaudi/pull/187).  I think the issue is caused by the following issue.  GaudiLlavaNextForConditionalGeneration 's functions are defined for pipeline generate in optimal-habana. There are some differences here, the return value of foward function is different; and in tgi-gaudi, image placeholder \<image\> has expanded to the size of image_features when sent to GaudiLlavaNextForConditionalGeneration , so  GaudiLlavaNextForConditionalGeneration  needs to modify his functions definition. 
Can you help to review  [PR187](https://github.com/huggingface/tgi-gaudi/pull/187)? See how to merge two patches. 
Thanks a lot.

**Comment by mandy-li** [comment]
@regisss , can we close this PR since llava_next is enabled in PR#187.

**Comment by regisss** [comment]
> @regisss , can we close this PR since llava_next is enabled in PR#187.

Will do once the other PR is merged, probably by the end of the week

**Comment by regisss** [comment]
Closing this one as #187 was merged and adds support for Llava-next.

**Pull request closed without merging**
