### PR TITLE
Updated Readme to use flash attention for llama

### PR DESCRIPTION
**Pull request by tthakkal**
# What does this PR do?

- Added parameters that improve performance to llama example commands
- Updated BATCH_BUCKET_SIZE and --max-batch-size parameters to match with bf16 run for fp8

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by mgonchar — APPROVED** [review]
LGTM

**Review by leopck — APPROVED** [review]
Sync-ed with Thanaji about this, as I saw some perf drop but the intention here is to align the configs rather than showcasing the best performance between BF16 and FP8. LGTM

**Review by mandy-li — APPROVED** [review]
LGTM. @regisss , please merge if it looks good to you too. thanks

**Comment by mandy-li** [comment]
@regisss , pls approve and merge if ok.

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
