### PR TITLE
V1.2.2 release

### PR DESCRIPTION
**Pull request by yafshar**
# What does this PR do?

- Add extra check to prevent failure on models (like mixtral) which do not have `bypass_hpu_graphs` optional arguments in the interface.
- The PR has been tested successfully on 

Fixes # (issue)

- https://github.com/huggingface/tgi-gaudi/issues/127

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@kdamaszk

### CODE REVIEW

**Comment by yafshar** [comment]
@kdamaszk, if you are working on this branch. I can help following on this PR

**Comment by yafshar** [comment]
This PR has the solution for HPU Graph issue reported in https://github.com/huggingface/tgi-gaudi/issues/130

**Comment by hsubramony** [comment]
@yafshar did you try the env variable 

ENABLE_HPU_GRAPH | True/False | True | Enable hpu graph or not

also please retry the issue on latest docker 1.15.1 + https://github.com/huggingface/tgi-gaudi/pull/134

**Comment by yafshar** [comment]
> @yafshar did you try the env variable
> 
> ENABLE_HPU_GRAPH | True/False | True | Enable hpu graph or not

For workloads which have an issue, disabling the hpu graph by env variable works. But it has the performance effect.

> also please retry the issue on latest docker 1.15.1 + #134
The issue exists there as well. 

One point is that https://github.com/huggingface/tgi-gaudi/pull/134 uses the merge from tgi_gaudi:habana-main which has the dill patch for dill 0.3.7, we should update that to 0.3.8 to have the correct dependencies.

**Comment by yafshar** [comment]
@regisss, we can close this PR in favor of https://github.com/huggingface/tgi-gaudi/pull/134

**Pull request closed without merging**
