### PR TITLE
Rebase with TGI 2.0.1

### PR DESCRIPTION
**Pull request by kdamaszk**
# What does this PR do?

Rebases with TGI 2.0.1

### CODE REVIEW

**Comment by kdamaszk** [comment]
@regisss please review. It would be nice to not squashing the commits, like we did last time.

**Comment by schoi-habana** [comment]
this addresses the issue where tgi grammar with tools fails to identify function names.

**Review by regisss — APPROVED** [review]
LGTM!

@kdamaszk I'll wait for you to publish the release before pushing a Docker image for v2.0.1 right?

**Comment by kdamaszk** [comment]
@regisss right, I thought we will wait for optimum-habana 1.12.0

**Comment by regisss** [comment]
Sure, let's do that

**Pull request merged**
