### PR TITLE
Warmup all decode buckets

### PR DESCRIPTION
**Pull request by kdamaszk**
# What does this PR do?

Adds additional warmup stage to warmup all decode buckets.

### CODE REVIEW

**Comment by kdamaszk** [comment]
@regisss please review

**Review by jczaja — APPROVED** [review]
LGTM

**Comment by mandy-li** [comment]
We tested and it fixes the problem. @regisss , please review at your earliest convenience. thanks

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
