### PR TITLE
Fix the generate_stream crash in concurrent query

### PR DESCRIPTION
**Pull request by yuanwu2017**
The requests number is different with the new batch size after concat. Need append the dummy parameters for the dummy requests.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by kdamaszk** [comment]
@yuanwu2017 looks good to me. However, can you describe the scenario when this error occurs?
@jkaniecki @szutenberg please review

**Review by jkaniecki — APPROVED** [review]

**Comment by jkaniecki** [comment]
@kdamaszk tested - approved, This solves issue with tensor dim's mismatch. It appears when using some non-default request parameters (like temperature != 1.0 etc) and setting do_sample inside next_token_chooser. That path uses HeterogeneousSampling , which was not validated before.

**Comment by jkaniecki** [comment]
@regisss Please, review

**Comment by yuanwu2017** [comment]
@jkaniecki is right. The failed case used some parameters as following.  
Parameters:
`generate{parameters=GenerateParameters { best_of: None, temperature: Some(0.01), repetition_penalty: Some(1.03), top_k: Some(10), top_p: Some(0.95), typical_p: Some(0.95), do_sample: false, max_new_tokens: Some(32), return_full_text: Some(false), stop: [], truncate: None, watermark: false, details: false, decoder_input_details: false, seed: Some(42), top_n_tokens: None }}`

```
terminate called after throwing an instance of 'c10::Error'
  what():  The size of tensor a (8) must match the size of tensor b (2) at non-singleton dimension 0
Exception raised from infer_size_impl at /npu-stack/pytorch-fork/aten/src/ATen/ExpandUtils.cpp:31 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xae (0x7fc267b9fd1e in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7fc267b54b39 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: at::infer_size(c10::ArrayRef<long>, c10::Ar
```
If you want to reproduce it, you can use [this script](https://github.com/yuanwu2017/llm-dbg/blob/main/run_tgi_stream_benchmark.sh)

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
