### PR TITLE
Adjust max_new_tokens in warmup

### PR DESCRIPTION
**Pull request by kdamaszk**
# What does this PR do?

Modifies `max_new_tokens` in warmup so all decode batch sizes can be covered.

### CODE REVIEW

**Comment by kdamaszk** [comment]
@regisss please review

**Comment by mandy-li** [comment]
we tested, it fixed the initial crashing issue for large BS. @regisss , please merge before we release tgi-gaudi for synapse 1.16.

**Review by mandy-li — APPROVED** [review]
LGTM

**Review by schoi-habana — APPROVED** [review]
validated. lgtm

**Pull request merged**
