### PR TITLE
Add missing cargo.lock file to Dockerfile

### PR DESCRIPTION
**Pull request by yafshar**
# What does this PR do?

Add missing `cargo.lock` file to Dockerfile to prevent the failures because of old rustc version.

## Who can review?

@kdamaszk 
@regisss

### CODE REVIEW

**Comment by vidyasiv** [comment]
@yafshar , can you check if https://github.com/huggingface/tgi-gaudi/pull/162 fixed the issue for you? It did for me.

**Comment by yafshar** [comment]
@vidyasiv this is the same issue, but that solution is not correct! The lock file should be available preparing the [recipe](https://github.com/huggingface/tgi-gaudi/blob/a9b77b7037ce4bf93724453ba7bbbb164760b128/Dockerfile#L12), otherwise the same error will happen again.

**Comment by kdamaszk** [comment]
@yafshar please change target branch to habana-main

**Comment by regisss** [comment]
I changed the target branch. There are some merge conflicts, can you check them @yafshar please?

**Comment by yafshar** [comment]
@regisss, I resolved the conflict, but this branch targeting Synapse 1.15.0 & 1.15.1 we should not merge it to habana-main. I will revert those changes

**Comment by yafshar** [comment]
@regisss, so can we merge it with the v2.0.0-release? Do we have any patch release for that version? There are also fixes from Libin https://github.com/huggingface/tgi-gaudi/tree/libint/fix_input_ids_crash that can be added here if we want to have a patch release for v2.0.0-release

**Comment by regisss** [comment]
@yafshar The problem is that we try to align with TGI for version numbers. And since we already released v2.0.0 and v2.0.1, these patches should be merged into main so that they can be part of our v2.0.2 release.

**Comment by kdamaszk** [comment]
> @yafshar The problem is that we try to align with TGI for version numbers. And since we already released v2.0.0 and v2.0.1, these patches should be merged into main so that they can be part of our v2.0.2 release.

+1 from me. I would suggest to use always latest release, as there are still some bug fixes and improvements. We didn't plan to do any patch releases.

**Pull request closed without merging**
