### PR TITLE
Schoi/llama3.1 tokenizer

### PR DESCRIPTION
**Pull request by endomorphosis**
this bumps dependencies and is tested for llama 3.1 8b, 70b, but not yet 405b, but it relies on optimum_habana git repository because no release has been made yet.

### CODE REVIEW

**Comment by mandy-li** [comment]
@endomorphosis . thanks for PR. after optimum-habana is released, we will bump up all required package version and release with synapse 1.17 and optimum-habana 1.13.0

**Review by schoi-habana — CHANGES_REQUESTED** [review]
@endomorphosis thanks for the changes. However, the repo maintainer will be bumping the packages versions shortly after https://github.com/huggingface/tgi-gaudi/pull/187 is merged. I suggest you consider dropping this PR and waiting for further updates

**Comment by endomorphosis** [comment]
yes, I understand that's why i didn't try to merge it into main, I was testing a bug in the package that relates to quantization, to quantize llama 405b to fp8, and I wanted a stable fork to test from.

**Comment by mandy-li** [comment]
Closing without merge. if just for your own testing purpose, please just keep the code changes in your fork repo

**Pull request closed without merging**
