### PR TITLE
Prefer prefill instead of decode when max_waiting_tokens==0

### PR DESCRIPTION
**Pull request by mrs303**
# What does this PR do?

It changes the batching_task function from router/src/infer.rs to prefer getting new batch and doing perfill in case max_waiting_tokens==0.
This is achieved by wrapping the logic for getting new batch with a loop.
The loop is broken when:
 - there was no batch to get
 - max_waiting_tokens != 0 what results in preserving the old behaviour

### CODE REVIEW

**Comment by mrs303** [comment]
It is best to review changes ignoring whitespace changes

**Review by kdamaszk — APPROVED** [review]

**Review by kdamaszk — CHANGES_REQUESTED** [review]
Make sure the batch size does not exceed the one limited by max-batch-total-tokens

**Review by kdamaszk — APPROVED** [review]
LGTM!

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
