### PR TITLE
Enable quantization with INC 

### PR DESCRIPTION
**Pull request by tthakkal**
# What does this PR do?
Adds option to quantize model with Intel Neural Compressor

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by mandy-li** [comment]
@kdamaszk , not sure if you have bandwidth to review this PR. The difference between this PR and your PR is we set INC enablement to true by default as alignment with OH

**Review by kdamaszk — COMMENTED** [review]
LGTM
Please verify this also by running most common models with INC. I wasn't able to do this before

**Review by pk1d3v — APPROVED** [review]
LGTM!

`finish_quantization_measurements` is not called anywhere, as I see it, right?

**Review by mgonchar — APPROVED** [review]
LGTM

**Comment by tthakkal** [comment]
> LGTM!
> 
> `finish_quantization_measurements` is not called anywhere, as I see it, right?

yes measurements only happen in optimum-habana

**Review by leopck — APPROVED** [review]
I ran these changes and works well for me too :)

**Review by regisss — APPROVED** [review]
LGTM!
This one should be merged once the Dockerfile is updated with Synapse 1.17 right?

**Comment by mandy-li** [comment]
> LGTM! This one should be merged once the Dockerfile is updated with Synapse 1.17 right?

Yes, that's right

**Review by mandy-li — APPROVED** [review]
LGTM

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
