### PR TITLE
Log exceptions to debug log

### PR DESCRIPTION
**Pull request by madamczyk-intel**
Log exceptions to debug log when DBG_TRACE_FILENAME is specified

### CODE REVIEW

**Comment by madamczyk-intel** [comment]
@kdamaszk please review

**Review by kdamaszk — APPROVED** [review]
LGTM!

**Comment by kdamaszk** [comment]
@madamczykhabana could you rebase this PR? We can merge it

**Comment by madamczyk-intel** [comment]
@kdamaszk ready for merge :)

**Review by kdamaszk — APPROVED** [review]

**Pull request merged**
