### PR TITLE
Downgrade sympy to match synapaseAI 1.18 base image

### PR DESCRIPTION
**Pull request by tthakkal**
# What does this PR do?
- Fix auto upgrading of torch version when using synapse 1.18 PyTorch 2.4.0 base image,
tested with base image artifactory-kfs.habana-labs.com/docker-local/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.0:1.18.0-308
`torch 2.4.0a0+git63a653e requires sympy==1.12.1, but you'll have sympy 1.13.2 which is incompatible.`
- Removed assert that's causing failure at initialization.

Fix for bugs 
-  https://jira.habana-labs.com/browse/SW-198625
- https://jira.habana-labs.com/browse/SW-198136

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by mandy-li — APPROVED** [review]
LGTM

**Comment by regisss** [comment]
@tthakkal @mandy-li Should this be merged now or should we wait for the release of Synapse 1.18 ?

**Comment by mandy-li** [comment]
> @tthakkal @mandy-li Should this be merged now or should we wait for the release of Synapse 1.18 ?

@regisss , i don't think we need to wait for 1.18. This PR fixes blocker for our QA test for 1.18, but it should work in 1.17 as well

**Review by regisss — APPROVED** [review]
LGTM!

**Pull request merged**
